/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_e_science_git_ivahan0788_NativeSorter */

#ifndef _Included_pl_e_science_git_ivahan0788_NativeSorter
#define _Included_pl_e_science_git_ivahan0788_NativeSorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_e_science_git_ivahan0788_NativeSorter
 * Method:    sort01
 * Signature: ([Ljava/lang/Double;Ljava/lang/Boolean;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_e_1science_git_ivahan0788_NativeSorter_sort01
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     pl_e_science_git_ivahan0788_NativeSorter
 * Method:    sort02
 * Signature: ([Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_e_1science_git_ivahan0788_NativeSorter_sort02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     pl_e_science_git_ivahan0788_NativeSorter
 * Method:    sort03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_e_1science_git_ivahan0788_NativeSorter_sort03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
